### ISSUE TITLE
About Us Admin Page

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#167]
@bschmitz9 I completed the aboutUs main site page. Youll need to copy the ngIfs and what not to the admin page and get the edit modals working. I think there is one section on the admin page not loading properly. The rest appears correct.

**Comment by bschmitz9** [comment]
@dolson334 I'm only seeing Employee Intro Header with the intro paragraph. Features Intro Header with the intro paragraph and the two features listed. And then Video Intro Header with the intro summary paragraph and the video. I don't see anything else. On the main site I don't see the Employee section at all. Can you double check on your end?

**Comment by bschmitz9** [comment]
@dolson334 can you also add "featuresIntroSummary" to the database? I hard coded it in the getAboutInfo function with the rest of the getPageText calls.

**Comment by dolson334** [comment]
@bschmitz9 are you seeing the pictures now?

**Comment by bschmitz9** [comment]
@dolson334 I'm still not seeing them here

**Comment by dolson334** [comment]
@bschmitz9 are you not seeing these pictures like I am ?? 

<img width="539" alt="aboutus" src="https://user-images.githubusercontent.com/16144247/53778155-6aa02080-3ec1-11e9-8fcb-6792eab929cf.png">

**Comment by dolson334** [comment]
@bschmitz9 clear your cache

**Comment by bschmitz9** [comment]
@dolson334 I looked into this a little bit. My "resort.pictures" array is empty and aboutUs.pictures is null. So if the getPicture and getPictureObject functions are looking for matches in resort.getPictures obviously there isn't going to be any.

**Comment by dolson334** [comment]
@bschmitz9 Can you try this again. Clean build all that. this is really weird because it is working for me, even when I build the way you build.

**Comment by bschmitz9** [comment]
@dolson334 still not getting anything in the response that has pictures or videos. Both are empty arrays.

**Comment by dolson334** [comment]
@bschmitz9 the admin about was throwing a javascript error. I think I fixed this so take a look. On the admin site there are some issues with the Feature Intro pictures and texts. Can you fix this? The data should all be there.

**Comment by bschmitz9** [comment]
@dolson334 I still don't get pictures. I never had any javascript errors on my end.

**Comment by dolson334** [comment]
On the admin about page or the main about page ?

**Comment by bschmitz9** [comment]
both

**Comment by dolson334** [comment]
@bschmitz9 whats the main site url you are using?

**Comment by bschmitz9** [comment]
@dolson334 I'm at localhost:4200/about

**Comment by dolson334** [comment]
@bschmitz9  do you go to localhost:4200 first?

**Comment by bschmitz9** [comment]
@dolson334  I just tried going to the site like a normal user would. Loading up the home page first and then clicking on the about link in the footer. My pictures array is empty. I have all other resort data but pictures.

**Comment by bschmitz9** [comment]
@dolson334 are you sure pictures are being picked up in your response and nothing is clearing them out anywhere?

**Comment by dolson334** [comment]
@bschmitz9 here is what my this.resort looks like when I console.log it in the getAboutData() function in the mainSite/about.component.ts file. 
<img width="825" alt="aboutPic" src="https://user-images.githubusercontent.com/16144247/54953470-48288280-4f16-11e9-98da-162492ca7bd6.png">

**Comment by dolson334** [comment]
@bschmitz9 Ok, I think I now know why this ws happenning (dont wanna jynx it though). Basically, it was a .gitignore thing (if this works). Take a peak again and see if you can see the about us pictures (clean and build completely).

**Comment by bschmitz9** [comment]
@dolson334 I have the pictures so I'm going  to close this and I'll open other tickets for issues.

**Comment by dolson334** [comment]
Awesome. There will be a bunch as I haven’t really set the approve and I’m
approve up yet
