### ISSUE TITLE
Contact Us remaingPendingChanges in preview

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#212]
If I approve an individual change on the Contact Us I get redirected back to the admin even when there are additional pending changes on the preview.

Reason: remainingPendingChanges comes back as false when it should be true.

**Comment by bschmitz9** [comment]
@dolson334 replicate it by:

1. Updating intro
2. Updating picture or contact info or both.
3. Approve the intro only in the preview.

Approving only the intro is approving everything else on the page in the preview, causing remaingPendingChanges to be false.

**Comment by bschmitz9** [comment]
@dolson334  same thing happens if I update picture and contact info and then approve the picture first. It updates the contact info as well.

**Comment by dolson334** [comment]
@bschmitz9 Ok i think this is fixed. Can you try again and close if so.?

**Comment by bschmitz9** [comment]
@dolson334 this works fine if I have a pending intro and pending photo and I update the photo first. But if I approve the intro before the photo it redirects me back to the admin and still shows the preview button and then if I go to the preview it still shows the picture as pending.

Same exact situation if I have a pending intro and a pending address/email/phone number change.


If I have a pending photo and pending address change/email/phone number. and I update the photo first it updates everything on the page and redirects me back to the admin. But if I update the contact info first it works great.

**Comment by dolson334** [comment]
@bschmitz9 We need to have a call on this. I am seeing this as working but maybe I am not understanding your recreation path.

**Comment by bschmitz9** [comment]
@dolson334 this one I'm still not seeing working for me.

1. Update the page header and the page intro.
2. Update the picture - background image.
3. Update a couple things in the contact info (i.e. address, state, zip code).
4. Go to the preview and approve the intro only. 

For me it redirects me back to the admin? Then in the admin it still shows the "View & Approve Changes" button. Then if I go back to the preview, and approve the background image, it redirects me back to the admin with both the picture and the address updated.

**Comment by dolson334** [comment]
@bschmitz9 Ok so from what you are saying there are 2 issues. I believe one for me and one for you. 

1. After you approve the intro changes it should keep you on the preview page. The endpoint returns this.isContactUsStaged as true which should keep us on the preview page. So I believe something is wrong with the angular page. @bschmitz9 Can you look into that?

2. Approving the backround image approves the resort info. I will fix this.

**Comment by bschmitz9** [comment]
@dolson334 That's not what keeps you on the preview page. You need to check "remainingPendingChanges" in the "updateIntroduction" function on the main site. That is coming back as undefined which is causing the page to redirect back to the admin. That value should be true.

**Comment by dolson334** [comment]
Ok I’ll look. Take a look at my #2. Should be working now but I only tested
once

**Comment by dolson334** [comment]
@bschmitz9 I made some changes and this should be all set now. Can u give it a try?
